# Generated by Django 3.0.7 on 2020-06-22 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITSP_Teams',
            fields=[
                ('Team_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Team_Name', models.CharField(max_length=45)),
                ('memeber1', models.CharField(max_length=100)),
                ('memeber2', models.CharField(max_length=100)),
                ('email1', models.EmailField(max_length=100)),
                ('email2', models.EmailField(max_length=100)),
                ('Topic', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
