# Generated by Django 3.0.7 on 2020-06-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITSP_Teams',
            new_name='ITSP',
        ),
    ]
