# Generated by Django 3.0.7 on 2020-06-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0002_auto_20200622_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itsp',
            old_name='Team_Name',
            new_name='Team',
        ),
    ]
