# Generated by Django 3.0.7 on 2020-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSP', '0005_auto_20200622_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsp',
            name='Team_ID',
        ),
        migrations.AddField(
            model_name='itsp',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
